df<-read.table("household_power_consumption.txt",header=TRUE,sep=';',dec='.',na.strings='?')
Sys.setlocale("LC_TIME", "English")
df$datetime<-as.Date(strptime(paste(df$Date,df$Time,sep=' '),format='%d/%m/%Y %H:%M:%S'))
df1<-subset(df,datetime>="2007-02-01" & datetime <="2007-02-02")
png(file = "plot4.png", width = 480, height = 480, bg = "transparent")
par(mfcol=c(2,2),mai = c(0.6,0.6,0.6,0.6),cex=0.7)
#plot (1,1)
with(df1,plot(Global_active_power,type="l",xaxt='n',xlab="",ylab="Global Active Power (kilowatts)"))
axis(1,at=c(1,nrow(df1)/2,nrow(df1)),labels=c('Thu','Fri','Sat'))
#plot (2,1)
with(df1,plot(Sub_metering_1,type="l",xaxt='n',xlab="",ylab="Energy sub metering"))
with(df1,lines(Sub_metering_2,type='l',col='red'))
with(df1,lines(Sub_metering_3,type='l',col='blue'))
legend("topright",col=c('black','red','blue'),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3" ),lty=1,bty="n")
axis(1,at=c(1,nrow(df1)/2,nrow(df1)),labels=c('Thu','Fri','Sat'))
#plot (1,2)
with(df1,plot(Voltage,type="l",xaxt='n',xlab='datetime',ylab="Voltage"))
axis(1,at=c(1,nrow(df1)/2,nrow(df1)),labels=c('Thu','Fri','Sat'))
#plot (2,2)
with(df1,plot(Global_reactive_power,type="l",xaxt='n',xlab='datetime'))
axis(1,at=c(1,nrow(df1)/2,nrow(df1)),labels=c('Thu','Fri','Sat'))
dev.off()
