df<-read.table("household_power_consumption.txt",header=TRUE,sep=';',dec='.',na.strings='?')
Sys.setlocale("LC_TIME", "English")
df$Time<-as.Date(strptime(paste(df$Date,df$Time,sep=' '),format='%d/%m/%Y %H:%M:%S'))
df1<-subset(df,Time>="2007-02-01" & Time <="2007-02-02")
png(file = "plot3.png", width = 480, height = 480, bg = "transparent")
with(df1,plot(Sub_metering_1,type="l",xaxt='n',xlab="",ylab="Energy Sub metering"))
with(df1,lines(Sub_metering_2,type='l',col='red'))
with(df1,lines(Sub_metering_3,type='l',col='blue'))
legend("topright",col=c('black','red','blue'),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3" ),lty=1)
axis(1,at=c(1,nrow(df1)/2,nrow(df1)),labels=c('Thu','Fri','Sat'))
dev.off()